odeReportsApi:
  name: ode-reports-api
  imageRepository:  cosysdev.azurecr.io/ode-reports-api
  service:
    port: 80
  probes:
    enabled: false
  ingress:
    host: api.mound-rd.cosysdev.com
  kafka:
    groupId: 'reports'
  resources: {}